User endpoint
soniasonia/meal-tracker pull request #2
Opened 2020-07-06 18:06 UTC by soniasonia

2020-07-06 19:02 UTC, m4r3x requested changes

2020-07-06 19:02 UTC, m4r3x commented on backend/backend/settings.py
> +ALLOWED_HOSTS = ['0.0.0.0']
From django docs: 
> When DEBUG is True and ALLOWED_HOSTS is empty, the host is validated against ['localhost', '127.0.0.1', '[::1]'].

My understanding is that to keep app secure it must be explicity set to owned IP address, so no need to set it up until first production deployment.

2020-07-06 19:02 UTC, m4r3x commented on frontend/src/App.js
> +    const isToken = localStorage.getItem("token") ? true : false;
```suggestion
    return localStorage.getItem("token") && this.verifyToken();
```

2020-07-06 19:02 UTC, m4r3x commented on frontend/src/App.js
> +        localStorage.removeItem("token");
shouldnt u also change state of isLoggedIn? Same in catch block

2020-07-06 19:02 UTC, m4r3x commented on frontend/src/App.js
> +    axios.get(APP_URL + '/api/user/logout/', {
change promise to async

2020-07-06 19:02 UTC, m4r3x commented on frontend/src/App.js
> +import React from "react";
Remember to rm all console logs after final version

2020-07-06 19:02 UTC, m4r3x commented on backend/tests/test_user_api.py
> +            'username': 'sebix',
Lets create test tables for this test suite, this will simplify this file a lot and will help with future tests.

2020-07-06 19:03 UTC, m4r3x commented on frontend/src/App.js
> +    this.setState({ isLoggedIn: true });
Call setState only once

2020-07-07 19:01 UTC, soniasonia commented on backend/backend/settings.py
> +ALLOWED_HOSTS = ['0.0.0.0']
It has to be added, otherwise you get this message:
Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.

2020-07-07 19:06 UTC, soniasonia commented on frontend/src/App.js
> +        localStorage.removeItem("token");
It is false by default, that's why only success updates the state

2020-07-07 19:08 UTC, soniasonia commented on frontend/src/App.js
> +    axios.get(APP_URL + '/api/user/logout/', {
OK

2020-07-07 20:18 UTC, soniasonia commented on frontend/src/App.js
> +    const isToken = localStorage.getItem("token") ? true : false;
OK

2020-07-16 18:18 UTC, m4r3x approved these changes

2020-07-16 18:27 UTC, merged